name: Laravel

on:
  push:
    branches: [ "main" ]


jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
     - name: Test Application
       uses: appleboy/ssh-action@v0.1.2
       with:
        host: ${{ secrets.SSH_HOST_PROD }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /laravel/app # navigate into the folders
          git pull
          php artisan cache:clear
          php artisan config:clear
          php artisan view:clear
          php artisan route:clear
